### PR TITLE
Fix add to queue crash and run.sh

### LINKED ISSUE #1333: 7.9.0 - "Add to queue" crashes Tauon
As in the title. Returning error :

```bash
Traceback (most recent call last):
  File "/usr/bin/tauonmb", line 5, in <module>
    from tauon.__main__ import main
  File "/usr/lib/python3.12/site-packages/tauon/__main__.py", line 478, in <module>
    from tauon.t_modules import t_main
  File "/usr/lib/python3.12/site-packages/tauon/t_modules/t_main.py", line 46744, in <module>
    queue_box.draw(0, gui.panelY + pl_box_h, gui.lspw, full - pl_box_h)
  File "/usr/lib/python3.12/site-packages/tauon/t_modules/t_main.py", line 39446, in draw
    self.draw_card(x, y, w, h, yy, track, fq[i], db)
  File "/usr/lib/python3.12/site-packages/tauon/t_modules/t_main.py", line 39204, in draw_card
    if fqo[3] == 0:
       ~~~^^^
TypeError: 'TauonQueueItem' object is not subscriptable
```

### PR DESCRIPTION
**Pull request by C0rn3j**
Fixes #1333

Fixes issues introduced in #1330, sans passing args to tauon executable which is not necessary at the moment.

Adds a bit more typing.

### CODE REVIEW

**Comment by RSKYS** [comment]
For some reason I guess it didn't allow me to review last time and doesn't matter either.

run.sh was good the way it was, let it be pass args. 
Since we've been used as old method of building script. I don't want to do `echo "3" | run.sh` instead of simply `run.sh pipe`, way messy.

**Comment by RSKYS** [comment]
Also told you the reason why I didn't input them in showing options, I think I'm gonna change it that run.sh does main() but if args passed, it does winbuild, compile stuff, etc.

**Comment by C0rn3j** [comment]
> I don't want to do echo "3" | run.sh

`./run.sh 3`

> let us pass args.

You're welcome to build on top of this to functionality before #1330 to be able to pass args to `tauonmb` (used to be via `${@}`), though it seems to me you might be misunderstanding what I meant in the OP and thinking args broke in general? 

It still works fine for selection.

**Comment by Lorsoen** [comment]
It does not completly fix the issue unfortunately. This time, it crashes to : 

```bash
Traceback (most recent call last):
  File "/home/lorenzo/Documents/Tauon/.venv/bin/tauonmb", line 5, in <module>
    from tauon.__main__ import main
  File "/home/lorenzo/Documents/Tauon/.venv/lib/python3.12/site-packages/tauon/__main__.py", line 478, in <module>
    from tauon.t_modules import t_main
  File "/home/lorenzo/Documents/Tauon/.venv/lib/python3.12/site-packages/tauon/t_modules/t_main.py", line 47926, in <module>
    track = pctl.get_track(gui.toast_queue_object[0])
                           ~~~~~~~~~~~~~~~~~~~~~~^^^
TypeError: 'TauonQueueItem' object is not subscriptable
```

**Comment by C0rn3j** [comment]
@Lorsoen Fix'd

**Comment by Lorsoen** [comment]
```bash
Traceback (most recent call last):
  File "/home/lorenzo/Documents/Tauon/.venv/bin/tauonmb", line 5, in <module>
    from tauon.__main__ import main
  File "/home/lorenzo/Documents/Tauon/.venv/lib/python3.12/site-packages/tauon/__main__.py", line 478, in <module>
    from tauon.t_modules import t_main
  File "/home/lorenzo/Documents/Tauon/.venv/lib/python3.12/site-packages/tauon/t_modules/t_main.py", line 46319, in <module>
    playlist_render.full_render()
  File "/home/lorenzo/Documents/Tauon/.venv/lib/python3.12/site-packages/tauon/t_modules/t_main.py", line 35203, in full_render
    line_render(
  File "/home/lorenzo/Documents/Tauon/.venv/lib/python3.12/site-packages/tauon/t_modules/t_main.py", line 34355, in line_render
    if item[3] == 0:  # Only show mark if track type
       ~~~~^^^
TypeError: 'TauonQueueItem' object is not subscriptable
```

:sweat_smile:

**Comment by C0rn3j** [comment]
Maybe maybe maybe?

**Comment by Lorsoen** [comment]
```bash
Traceback (most recent call last):
  File "/home/lorenzo/Documents/Tauon/.venv/bin/tauonmb", line 5, in <module>
    from tauon.__main__ import main
  File "/home/lorenzo/Documents/Tauon/.venv/lib/python3.12/site-packages/tauon/__main__.py", line 478, in <module>
    from tauon.t_modules import t_main
  File "/home/lorenzo/Documents/Tauon/.venv/lib/python3.12/site-packages/tauon/t_modules/t_main.py", line 46751, in <module>
    queue_box.draw(0, gui.panelY + pl_box_h, gui.lspw, full - pl_box_h)
  File "/home/lorenzo/Documents/Tauon/.venv/lib/python3.12/site-packages/tauon/t_modules/t_main.py", line 39514, in draw
    if item[3] == 0:
       ~~~~^^^
TypeError: 'TauonQueueItem' object is not subscriptable
```

Not not not!

**Comment by C0rn3j** [comment]
How about nooooooow?

**Comment by Lorsoen** [comment]
Almost. Crashes when adding an album to Queue : 

```bash
Traceback (most recent call last):
  File "/home/lorenzo/Documents/Tauon/.venv/bin/tauonmb", line 5, in <module>
    from tauon.__main__ import main
  File "/home/lorenzo/Documents/Tauon/.venv/lib/python3.12/site-packages/tauon/__main__.py", line 478, in <module>
    from tauon.t_modules import t_main
  File "/home/lorenzo/Documents/Tauon/.venv/lib/python3.12/site-packages/tauon/t_modules/t_main.py", line 47991, in <module>
    instance.render()
  File "/home/lorenzo/Documents/Tauon/.venv/lib/python3.12/site-packages/tauon/t_modules/t_main.py", line 14482, in render
    self.items[to_call].func(self.reference)
  File "/home/lorenzo/Documents/Tauon/.venv/lib/python3.12/site-packages/tauon/t_modules/t_main.py", line 15830, in add_album_to_queue_fc
    if p != pctl.get_track(item[0]).parent_folder_path:
                           ~~~~^^^
TypeError: 'TauonQueueItem' object is not subscriptable

```

**Comment by C0rn3j** [comment]
`item[0]` will be in my nightmares

**Comment by Lorsoen** [comment]
No crashes. Hooray :tada: :tada:

**Pull request merged**
